import numpy as np
In [ ]:
#1.生成一個等差數列，首數為0，尾數為20，公差為1的數列。
In [ ]:
#2.呈上題，將以上數列取出偶數。
In [ ]:
#3.呈1題，將數列取出3的倍數。

In [1]:
import numpy as np

In [6]:
A= np.arange(0,21,1)  #arange(起始值,終止值,間隔值)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [7]:
A[::2]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [8]:
A[0::3]

array([ 0,  3,  6,  9, 12, 15, 18])